services:
  litd1:
    image: lightninglabs/lightning-terminal:v0.13.3-alpha
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.31.1.1
    ports:
      - "18443:8443"
    volumes:
      - "litd1:/root/.lit"
      - "./conf/lit/lit.conf:/root/.lit/lit.conf"
    command: --lnd.externalip=172.31.1.1 --lnd.externalip=litd1:9735 --lnd.tlsextradomain=litd1 --lnd.alias=litd1 --lnd.color=#89CFF0

  litd2:
    image: lightninglabs/lightning-terminal:v0.13.3-alpha
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.31.1.2
    ports:
      - "28443:8443"
    volumes:
      - "litd2:/root/.lit"
      - "./conf/lit/lit.conf:/root/.lit/lit.conf"
    command: --lnd.externalip=172.31.1.2 --lnd.externalip=litd2:9735 --lnd.tlsextradomain=litd2 --lnd.alias=litd2 --lnd.color=#FFB347

# --- Additional services ---

  bitcoind:
    image: lncm/bitcoind:v27.0
    restart: unless-stopped
    networks:
      testing_net:
        ipv4_address: 172.31.9.1
    volumes:
      - "bitcoind:/data/.bitcoin"
      - "./conf/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf"

  blockgen:
    build: ./docker/blockgen
    command: [ "/bin/sh", "/app/blockgen.sh" ]
    networks:
      testing_net:
        ipv4_address: 172.31.9.2
    volumes:
      - "./docker/blockgen/blockgen.sh:/app/blockgen.sh"
    depends_on:
      - bitcoind

volumes:
  bitcoind:
  litd1:
  litd2:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16